image: docker:latest
services:
  - docker:dind

stages:
  - build
  - publish

maven-build:
  image: maven:3.8.5-jdk-11-slim
  stage: build
  script: 
    - "cd ConfigServer"
    - "mvn package -B"
  artifacts:
    paths:
      - ConfigServer/target/*.jar

docker-build:
  stage: publish
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
    - export IMAGE_NAME="medez/config-server"
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}