image: docker:latest
services:
  - docker:dind

stages:
  - build
  - publish

maven-build:
  image: maven:3.8.5-jdk-11-slim
  stage: build
  script: 
    - "cd ConfigServer"
    - "mvn package -B"
  artifacts:
    paths:
      - ConfigServer/target/*.jar

docker-build:
  stage: publish
  script:
    - docker login -u medezz -p 00z1ngy0lk
    - export IMAGE_NAME="medezz/config-server"
    - docker build -t ${IMAGE_NAME}:1.0 .
    - docker push ${IMAGE_NAME}:1.0