image: docker:latest
services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - publish

maven-build:
  image: maven:3.8.5-jdk-11-slim
  stage: build
  script: 
    - "cd ConfigServer"
    - "mvn package -B"
  artifacts:
    paths:
      - ConfigServer/target/*.jar

docker-build:
  stage: publish
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  script:
    - export IMAGE_NAME="medez/config-server"
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}