image: docker:latest

services: 
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - push-images

build-main:
  stage: build
  image: maven:3.8.5-jdk-11-slim
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
  - mvn clean package -f AdminServer/pom.xml 
  - mvn clean package -f ConfigClient/pom.xml
  - mvn clean package -f ConfigServer/pom.xml
  - mvn clean package -f EurekaServer/pom.xml
  - mvn clean package -f AnotherClient/pom.xml
  - mvn clean package -f Gateway/pom.xml
  artifacts:
    paths:
      - AdminServer/target/*.jar
      - ConfigClient/target/*.jar
      - ConfigServer/target/*.jar
      - EurekaServer/target/*.jar
      - AnotherClient/target/*.jar
      - Gateway/target/*.jar
      
push-images-main:
  stage: push-images
  image: docker/compose:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose build
  - docker-compose push --ignore-push-failures